name: Download Artifact Pipeline

on:
  workflow_run:
    workflows:
      - Java Build Pipeline
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout artefacts-store branch
        uses: actions/checkout@v4
        with:
          ref: artefacts-store

